apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: ops-seal
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ops-seal
  template:
    metadata:
      labels:
        app: ops-seal
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "ops-seal"

        # Redis credentials
        vault.hashicorp.com/agent-inject-secret-redis-password: "kv/data/secret/redis"
        vault.hashicorp.com/agent-inject-template-redis-password: |
          {{`{{- with secret "kv/data/secret/redis" -}}`}}
          {{`{{ .Data.data.password }}`}}
          {{`{{- end }}`}}
        
        # MySQL credentials
        vault.hashicorp.com/agent-inject-secret-mysql-creds: "database/creds/ops-seal-db-role"
        vault.hashicorp.com/agent-inject-template-mysql-creds: |
          {{`{{- with secret "database/creds/ops-seal-db-role" -}}`}}
          {{`username={{ .Data.username }}`}}
          {{`password={{ .Data.password }}`}}
          {{`{{- end }}`}}

        # Terraform Cloud credentials
        vault.hashicorp.com/agent-inject-template-config-tfc-creds: |
          {{`{{- with secret "kv/data/secret/terraform-cloud" -}}`}}
          {{`export TFC_TOKEN="{{ .Data.data.token }}"`}}
          {{`{{- end }}`}}
        
        restartedAt: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
    spec:
      serviceAccountName: ops-seal
      automountServiceAccountToken: true
      containers:
        - name: ops-seal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: BASH_ENV
              value: /vault/secrets/config
