apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
  labels:
    app: ops-seal
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ops-seal
  template:
    metadata:
      labels:
        app: ops-seal
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "ops-seal"
        vault.hashicorp.com/agent-inject-secret-redis-password: "secret/data/redis"
        vault.hashicorp.com/agent-inject-template-redis-password: |
          {{`{{- with secret "secret/data/redis" -}}`}}
          {{`{{ .Data.data.password }}`}}
          {{`{{- end }}`}}
        restartedAt: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"  # Adds a timestamp
    spec:
      containers:
      - name: ops-seal
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}