replicaCount: 2

image:
  repository: ghcr.io/damienjburks/ops-seal
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  className: nginx
  enabled: true
  host: ops-seal.dsb-hub.local
  annotations:
    cert-manager.io/cluster-issuer: mkcert-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls:
    enabled: true
    host: ops-seal.dsb-hub.local  
    secretName: ops-seal-cert-tls

resources: {}
