replicaCount: 2

image:
  repository: ghcr.io/damienjburks/ops-seal
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: opsseal.dsb-hub.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls:
    enabled: false
    secretName: dsb-hub-tls

resources: {}
