name: Build Docker Image
on:
  workflow_call:

jobs:
  # Build Docker Image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Multi-Arch Docker Image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ops-seal:${{ github.sha }} .
